server:
  port: 9091

log:
  path: ./log

mybatis:
  mapper-locations: classpath:com/jffox/cloud/*.xml
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flink_feature_engine?useSSL=false
    username: feature_rw
    password: feature123
    filters: stat
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    validation-query: select 1


